components:
  schemas:
    GameInvitation:
      type: object
      properties:
        _id:
          type: string
          format: ^[a-f0-9]{24}$
        createdAt:
          type: string
          format: date-time
        fromUserId:
          type: string
          format: ^[a-f0-9]{24}$
        gameId:
          type: string
          format: ^[a-f0-9]{24}$
        toUserId:
          type: string
          format: ^[a-f0-9]{24}$
        updatedAt:
          type: string
          format: date-time
