apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database-api
  labels:
    app: database-api
spec:
  replicas: 3
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: database-api
        version: 0.0.29
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
      containers:
        - name: database-api
          image: tenlastic/database-api:0.0.29
          envFrom:
            - secretRef:
                name: database-api-environment-variables
          livenessProbe:
            httpGet:
              path: /databases
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: database-api
  labels:
    app: database-api
    service: database-api
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: database-api
