components:
  schemas:
    WebSocket:
      type: object
      properties:
        _id:
          type: string
          format: ^[a-f0-9]{24}$
        createdAt:
          type: string
          format: date-time
        namespaceId:
          type: string
          format: ^[a-f0-9]{24}$
        updatedAt:
          type: string
          format: date-time
        userId:
          type: string
          format: ^[a-f0-9]{24}$
