apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  namespace: redis
  labels:
    app: redis-commander
    service: redis-commander
spec:
  ports:
  - port: 8081
    name: http
  selector:
    app: redis-commander
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-commander
  namespace: redis
spec:
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: HTTP_USER
          value: admin
        - name: HTTP_PASSWORD
          value: admin
        - name: REDIS_HOST
          value: redis-redis-ha.redis.svc.cluster.local
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: redis-commander
  namespace: redis
spec:
  hosts:
  - redis.tenlastic.com
  gateways:
  - istio-system/istio-autogenerated-k8s-ingress
  http:
  - route:
    - destination:
        host: redis-commander
        port:
          number: 8081
