version: '2.1'
services:
  application:
    depends_on:
      - mongo_healthcheck
    environment:
      - MONGO_CONNECTION_STRING
      - MONGO_DATABASE_NAME
    links:
      - mongo
    working_dir: /usr/src/app/modules/change-data-capture/
