version: '2.1'
services:
  application:
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_CONNECTION_STRING
    links:
      - rabbitmq
    working_dir: /usr/src/app/modules/rabbitmq/
