apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.allow-http: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto https
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "1G"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - "*.tenlastic.com"
      secretName: letsencrypt-production
  rules:
    - host: api.tenlastic.com
      http:
        paths:
          - path: /
            backend:
              serviceName: documentation-ui
              servicePort: 80
          - path: /articles
            backend:
              serviceName: article-api
              servicePort: 3000
          - path: /connections
            backend:
              serviceName: authentication-api
              servicePort: 3000
          - path: /databases
            backend:
              serviceName: database-api
              servicePort: 3000
          - path: /friends
            backend:
              serviceName: social-api
              servicePort: 3000
          - path: /games
            backend:
              serviceName: game-api
              servicePort: 3000
          - path: /ignorations
            backend:
              serviceName: social-api
              servicePort: 3000
          - path: /logins
            backend:
              serviceName: authentication-api
              servicePort: 3000
          - path: /messages
            backend:
              serviceName: social-api
              servicePort: 3000
          - path: /namespaces
            backend:
              serviceName: namespace-api
              servicePort: 3000
          - path: /password-resets
            backend:
              serviceName: authentication-api
              servicePort: 3000
          - path: /releases
            backend:
              serviceName: release-api
              servicePort: 3000
          - path: /users
            backend:
              serviceName: authentication-api
              servicePort: 3000
    - host: minio.tenlastic.com
      http:
        paths:
          - path: /
            backend:
              serviceName: minio
              servicePort: 9000
    - host: platform.tenlastic.com
      http:
        paths:
          - path: /
            backend:
              serviceName: launcher-ui
              servicePort: 80
    - host: portal.tenlastic.com
      http:
        paths:
          - path: /
            backend:
              serviceName: portal-ui
              servicePort: 80
    - host: rabbitmq.tenlastic.com
      http:
        paths:
          - path: /
            backend:
              serviceName: rabbitmq-rabbitmq-ha
              servicePort: 15672
    - host: registry.tenlastic.com
      http:
        paths:
          - path: /
            backend:
              serviceName: docker-registry
              servicePort: 5000
    - host: sso.tenlastic.com
      http:
        paths:
          - path: /
            backend:
              serviceName: sso-ui
              servicePort: 80
    - host: www.tenlastic.com
      http:
        paths:
          - path: /
            backend:
              serviceName: home-ui
              servicePort: 80
