apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: release-api
  labels:
    app: release-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: release-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
      containers:
        - name: release-api
          image: tenlastic/release-api:0.0.37
          envFrom:
            - secretRef:
                name: release-api-environment-variables
          livenessProbe:
            httpGet:
              path: /releases
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: release-api
  labels:
    app: release-api
    service: release-api
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: release-api
