version: '2.1'
services:
  application:
    depends_on:
      - mongo_healthcheck
      - rabbitmq
    environment:
      - JWT_SECRET
      - MONGO_CONNECTION_STRING
      - MONGO_DATABASE_NAME
      - RABBITMQ_CONNECTION_STRING
    links:
      - mongo
      - rabbitmq
    ports:
      - 3002:3000
    working_dir: /usr/src/app/applications/database-api/
