version: 2.1

jobs:
  nodejs:
    docker:
      - image: node:10
      - image: wurstmeister/kafka:latest
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      - image: mongo:4
      - image: rabbitmq:latest
      - image: wurstmeister/zookeeper:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "./projects/nodejs/package.json" }}
      - run:
          name: Install Node Modules
          command: npm install
          working_directory: ./projects/nodejs/
      - run:
          name: Lerna Bootstrap
          command: npm run lerna bootstrap
          working_directory: ./projects/nodejs/
      - save_cache:
          key: dependency-cache-{{ checksum "./projects/nodejs/package.json" }}
          paths:
            - ./projects/nodejs/node_modules/
      - run:
          name: Lint
          command: npm run lerna run lint
          working_directory: ./projects/nodejs/
      - run:
          name: Build
          command: npm run lerna run build
          working_directory: ./projects/nodejs/
      - run:
          name: Test
          command: npm run lerna run -- --concurrency 1 test -- -- --coverage
          working_directory: ./projects/nodejs/
      - run:
          name: Test (E2E)
          command: npm run lerna run -- --concurrency 1 e2e
          working_directory: ./projects/nodejs/
      - run:
          name: Merge Test Results
          command: npm run merge:junit
          working_directory: ./projects/nodejs/
          when: always
      - run:
          name: Merge Code Coverage
          command: npm run merge:coverage
          working_directory: ./projects/nodejs/
          when: always
      - store_test_results:
          path: ./projects/nodejs/test-results/
      - store_artifacts:
          path: ./projects/nodejs/test-results/
          destination: test-results

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - nodejs:
          context: open-platform-review
