version: 2.1

commands:
  build_and_push_docker_image:
    parameters:
      directory:
        type: string
      label:
        type: string
      repository:
        type: string
    steps:
      - run:
          name: Build Docker Image (<< parameters.label >>)
          command: docker build -t << parameters.repository >>:latest ./
          working_directory: << parameters.directory >>
      - run:
          name: Push Docker Image (<< parameters.label >>)
          command: |
            IMAGE_ID=$(docker images << parameters.repository >>:latest --format "{{.ID}}")
            URL="tenlastic/<< parameters.repository >>"

            # Authenticate to Github Package Registry.
            docker login \
              -u "${DOCKER_HUB_USERNAME}" \
              -p "${DOCKER_HUB_PASSWORD}"

            # Tag and push version to Docker Hub.
            docker tag "${IMAGE_ID}" "${URL}:latest"
            docker push "${URL}:latest"

            # Tag and push latest version to Docker Hub.
            docker tag "${IMAGE_ID}" "${URL}:latest"
            docker push "${URL}:latest"

            URL="docker.pkg.github.com/tenlastic/open-platform/<< parameters.repository >>"

            # Authenticate to Github Package Registry.
            docker login docker.pkg.github.com \
              -u "${GITHUB_USER_EMAIL}" \
              -p "${GITHUB_TOKEN}"

            # Tag and push version to Github Package Registry.
            docker tag "${IMAGE_ID}" "${URL}:latest"
            docker push "${URL}:latest"

            # Tag and push latest version to Github Package Registry.
            docker tag "${IMAGE_ID}" "${URL}:latest"
            docker push "${URL}:latest"

  copy_directory:
    parameters:
      from:
        type: string
      label:
        type: string
      to:
        type: string
    steps:
      - run:
          name: << parameters.label >>
          command: |
            set -exu
            mkdir -p << parameters.to >>
            mv << parameters.from >> << parameters.to >>

  fetch_master_branch:
    steps:
      - run:
          name: Update Git Credentials
          command: |
            git config user.email $GITHUB_USER_EMAIL
            git config user.name $GITHUB_USER_NAME
      - run:
          name: Fetch Master Branch
          command: |
            BRANCH=$(git rev-parse --abbrev-ref HEAD)
            if [[ "$BRANCH" != "master" ]]; then
              git fetch --force origin "master:master"
              git pull --force origin "master:master"
              git show-branch
              git tag
            fi

  install_docker_client:
    steps:
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.3-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

  install_google_chrome:
    steps:
      - run:
          name: Install Google Chrome
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            apt-get update && apt-get install -yq google-chrome-stable

jobs:
  attempt_docker_setup:
    docker:
      - image: node:10
    steps:
      - setup_remote_docker
      - install_docker_client
      - run:
          name: Docker Info
          command: |
            export DOCKER_ENGINE_URL=$(echo $DOCKER_HOST | sed "s@tcp://@http://@g")
            curl --cert "${DOCKER_CERT_PATH}" -k "${DOCKER_ENGINE_URL}/images/json"

  continuous_integration:
    docker:
      - image: node:10
      - image: minio/minio:latest
        command: minio server /data
      - image: rabbitmq:latest
      - image: tenlastic/mongo-replica-set:latest
        environment:
          REPLICA_SET_HOSTNAME: localhost
      - image: wurstmeister/kafka:latest
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      - image: wurstmeister/zookeeper:latest
    steps:
      - install_google_chrome
      - checkout
      - fetch_master_branch
      - run:
          name: Install Lerna
          command: npm i -g lerna
          working_directory: ./projects/javascript/
      - restore_cache:
          key: root-packages-{{ checksum "./projects/javascript/package.json" }}
      - restore_cache:
          key: angular-packages-{{ checksum "./projects/javascript/angular/package.json" }}
      - restore_cache:
          key: nodejs-packages-{{ checksum "./projects/javascript/nodejs/package.json" }}
      - run:
          name: Lerna Bootstrap
          command: lerna bootstrap --concurrency 1 --include-dependencies --since
          working_directory: ./projects/javascript/
      - save_cache:
          key: root-packages-{{ checksum "./projects/javascript/package.json" }}
          paths: -./projects/javascript/node_modules/
      - save_cache:
          key: angular-packages-{{ checksum "./projects/javascript/angular/package.json" }}
          paths: -./projects/javascript/angular/node_modules/
      - save_cache:
          key: nodejs-packages-{{ checksum "./projects/javascript/nodejs/package.json" }}
          paths: -./projects/javascript/nodejs/node_modules/
      - run:
          name: Lint
          command: lerna run lint --concurrency 1 --include-dependencies --since
          working_directory: ./projects/javascript/
      - run:
          name: Build
          command: lerna run build --concurrency 1 --include-dependencies --since
          working_directory: ./projects/javascript/
      - run:
          name: Test
          command: lerna run test --concurrency 1 --include-dependencies --since
          working_directory: ./projects/javascript/
      - run:
          name: Merge Test Results
          command: |
            npm ci
            npm run merge:junit
            npm run merge:coverage

            npm ci --prefix ./modules/mochawesome-merge-json/
            npm run merge:mochawesome
          working_directory: ./projects/javascript/nodejs/
          when: always
      - store_test_results:
          path: ./projects/javascript/nodejs/test-results/
      - store_artifacts:
          path: ./projects/javascript/nodejs/test-results/
          destination: test-results

  publish_docker_images:
    docker:
      - image: node:10
    steps:
      - setup_remote_docker
      - install_docker_client
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Lerna
          command: npm i -g lerna
      - run:
          name: Build Docker Images
          command: lerna run --concurrency 1 docker:build
          working_directory: /tmp/workspace/projects/javascript/
      - run:
          name: Push Docker Images
          command: lerna run --concurrency 1 docker:push
          working_directory: /tmp/workspace/projects/javascript/

  publish_electron_applications:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install Lerna
          command: npm i -g lerna
          working_directory: /tmp/workspace/projects/javascript/
      - run:
          name: Lerna Bootstrap
          command: lerna bootstrap --concurrency 1 --include-dependencies --scope @tenlastic/*-ui --scope angular
          working_directory: /tmp/workspace/projects/javascript/
      - run:
          name: Install Electron Builder Dependencies
          command: lerna run --concurrency 1 electron:install
          working_directory: /tmp/workspace/projects/javascript/
      - run:
          name: Build and Publish Electron Applications
          command: lerna run --concurrency 1 electron:windows -- -- --publish always
          working_directory: /tmp/workspace/projects/javascript/

  publish_miscellaneous_docker_images:
    docker:
      - image: node:10
    steps:
      - setup_remote_docker
      - install_docker_client
      - checkout
      - build_and_push_docker_image:
          directory: ./
          label: Infrastructure Utilities
          repository: infrastructure-utilities
      - build_and_push_docker_image:
          directory: ./projects/javascript/nodejs/dockerfiles/mongo-replica-set/
          label: MongoDB Replica Set
          repository: mongo-replica-set

  publish_npm_modules:
    docker:
      - image: node:10
    steps:
      - checkout
      - run:
          name: Update Git Credentials
          command: |
            git config user.email $GITHUB_USER_EMAIL
            git config user.name $GITHUB_USER_NAME
      - run:
          name: Install Lerna
          command: npm i -g lerna
          working_directory: ./projects/javascript/
      - run:
          name: Lerna Bootstrap
          command: lerna bootstrap --concurrency 1
          working_directory: ./projects/javascript/
      - run:
          name: Build
          command: lerna run --concurrency 1 build
          working_directory: ./projects/javascript/
      - run:
          name: Publish Node Modules to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

            npm config set unsafe-perm true
            lerna publish \
              --exact \
              --message "javascript-v%v [skip ci]" \
              --tag-version-prefix javascript-v \
              --yes \
              patch
            npm config set unsafe-perm true
          working_directory: ./projects/javascript/
      - run:
          name: Publish Node Modules to Github
          command: |
            echo "@tenlastic:registry=https://npm.pkg.github.com" > ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc

            lerna publish \
              --registry https://npm.pkg.github.com \
              --yes \
              from-package
          working_directory: ./projects/javascript/
      - run:
          name: Delete Node Modules
          command: find . -name "node_modules" -exec rm -rf '{}' +
          working_directory: ./projects/javascript/
      - copy_directory:
          label: Persist Javascript Directory
          from: ./projects/javascript/*
          to: /tmp/workspace/projects/javascript/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - projects/javascript/

  terraform:
    docker:
      - image: hashicorp/terraform:0.11.13
    steps:
      - checkout
      - run:
          name: Apply Custom Roles
          command: |
            terraform init -backend-config="./backend.example.tfvars"
            terraform apply -auto-approve
          working_directory: ./gcp/terraform/custom-roles/
      - run:
          name: Apply Cluster
          command: |
            terraform init -backend-config="./backend.example.tfvars"
            terraform apply -auto-approve
          working_directory: ./gcp/terraform/cluster/

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - attempt_docker_setup
      # - continuous_integration:
      #     context: open-platform-review
      # - publish_miscellaneous_docker_images:
      #     filters:
      #       branches:
      #         only: master
      #     requires:
      #       - continuous_integration
      # - publish_npm_modules:
      #     filters:
      #       branches:
      #         only: master
      #     requires:
      #       - continuous_integration
      # - publish_docker_images:
      #     requires:
      #       - publish_npm_modules
      # - publish_electron_applications:
      #     requires:
      #       - publish_npm_modules
      # - terraform:
      #     filters:
      #       branches:
      #         only: master
      #     requires:
      #       - continuous_integration
