apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication-api
  labels:
    app: authentication-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: authentication-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
      containers:
        - name: authentication-api
          image: tenlastic/authentication-api:0.0.52
          envFrom:
            - secretRef:
                name: authentication-api-environment-variables
          livenessProbe:
            httpGet:
              path: /users
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 15
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-api
  labels:
    app: authentication-api
    service: authentication-api
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: authentication-api
