components:
  schemas:
    Game:
      type: object
      properties:
        _id:
          type: string
          format: ^[a-f0-9]{24}$
        allowedUserIds:
          type: array
          items:
            type: string
            format: ^[a-f0-9]{24}$
        createdAt:
          type: string
          format: date-time
        currentUserIds:
          type: array
          items:
            type: string
            format: ^[a-f0-9]{24}$
        description:
          type: string
        gameId:
          type: string
          format: ^[a-f0-9]{24}$
        heartbeatAt:
          type: string
          format: date-time
        maxUsers:
          type: integer
        metadata:
          type: object
        name:
          type: string
        password:
          type: string
        releaseId:
          type: string
          format: ^[a-f0-9]{24}$
        updatedAt:
          type: string
          format: date-time
        url:
          type: string
      required:
        - gameId
        - name
