components:
  schemas:
    ReleaseJob:
      type: object
      properties:
        _id:
          type: string
          format: ^[a-f0-9]{24}$
        createdAt:
          type: string
          format: date-time
        platform:
          type: string
          enum: windows64, windows32, mac64, mac32, linux64, linux32
        releaseId:
          type: string
          format: ^[a-f0-9]{24}$
        updatedAt:
          type: string
          format: date-time
