components:
  schemas:
    File:
      type: object
      properties:
        _id:
          type: string
          format: ^[a-f0-9]{24}$
        buildId:
          type: string
          format: ^[a-f0-9]{24}$
        compressedBytes:
          type: integer
        createdAt:
          type: string
          format: date-time
        md5:
          type: string
        path:
          type: string
        platform:
          type: string
          enum: [linux64, mac64, server64, windows64]
        uncompressedBytes:
          type: integer
        updatedAt:
          type: string
          format: date-time
