apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sso-ui
  labels:
    app: sso-ui
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: sso-ui
    spec:
      containers:
        - name: sso-ui
          image: tenlastic/sso-ui:0.0.69
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: sso-ui
  labels:
    app: sso-ui
    service: sso-ui
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: sso-ui
